services:
  root-config:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - angular-mfe
      - react-mfe
    volumes:
      - .:/app
    restart: always

  angular-mfe:
    build:
      context: ./angular-mfe
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./angular-mfe:/app
    restart: always

  react-mfe:
    build:
      context: ./react-mfe
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./react-mfe:/app
    restart: always
